[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/aniki/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    192.168.0.0/16
    FE80::/10
    ::1/128
    192.168.1.0/24
cors_domains:
    http://*.4sst.ru
    https://*.4sst.ru
    *.4sst.ru
    *://mainsail.4sst.ru
    *://localhost
    *://localhost:*

[octoprint_compat]

[history]

[file_manager]
# post processing for object cancel. Not recommended for low resource SBCs such as a Pi Zero. Default False
enable_object_processing: True

# this enables moonraker announcements for mainsail
[announcements]
subscriptions:
    mainsail

[power MainSwitch]
type: gpio
pin: gpiochip1/gpio117
value: False                 # Выключено при старте системы
shutdown_value: False        # Выключить при программном стопе Moonraker

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail]
path: /home/aniki/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[update_manager alp-klipper-printers]
managed_services: klipper
origin: https://github.com/lexanikitin/alp-klipper-printers.git
path: /home/aniki/alp-klipper-printers
primary_branch: main
type: git_repo

